# Generated by Django 3.0.6 on 2020-05-31 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200523_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['created']},
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='slug',
        ),
    ]
