# Generated by Django 3.0.6 on 2020-06-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200531_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_type',
            field=models.CharField(choices=[('S', 'Проповедь'), ('A', 'Статья'), ('P', 'Стих')], max_length=1),
        ),
    ]
