# Generated by Django 3.0.6 on 2020-06-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200601_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_type',
            field=models.CharField(choices=[('sermon', 'Проповедь'), ('article', 'Статья'), ('poem', 'Стих')], max_length=10),
        ),
    ]
